from toontown.coghq.SpecImports import *
GlobalEntities = {0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
10007: {'type': 'nodepath',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(329, -190, -42.790),
         'hpr': Vec3(90, 0, 0),
         'scale': 1},
 10008: {'type': 'nodepath',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(340, -195, -42.790),
         'hpr': Vec3(90, 0, 0),
         'scale': 1},
10006: {'type': 'securityCamera',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(329, -204, -42.790),
         'hpr': Vec3(90, 0, 0),
         'scale': 1,
         'accel': 5.0,
         'damPow': 10,
         'hideModel': 0,
         'maxVel': 15.0,
         'modelPath': 0,
         'projector': Point3(6, 6, 25),
         'radius': 5,
         'switchId': 0,
         'trackTarget1': 10007,
         'trackTarget2': 10008,
         'trackTarget3': 0},}
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
